server:  
  port: 9001
  
spring:
  application:
    name: micro1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DEFAULT_ZONE}
  instance:
    prefer-ip-address: ${PREFER_IP_ADDRESS:false}
    ipAddress : ${HOST_NAME:${spring.application.name}}
    hostname: ${HOST_NAME:${spring.application.name}}
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: ${LEASE_RENEWAL_INTERVAl_IN_SECONDS:10}
    leaseExpirationDurationInSeconds: ${LEASE_EXPIRATION_DURATIONIN_SECONDS:20}

#MY_SECRET: ${docker-secret-MY_SECRET}
    
# The "docker-secret.bind-path" property trigger the EnvironmentPostProcessor to load 
# the bind docker secrets as password property
#docker-secret:
#  bind-path: /run/secrets  

zuul:
  retryable: true
  ignored-patterns:
  - /api/greet-m1
  prefix: /api
  strip-prefix: true
  routes:
    micro2:
      path: /*
      service-id: micro2
    
    
    
DEFAULT_ZONE: http://naming-server:8761/eureka/ 
    